# Generated by Django 2.1.3 on 2018-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunicados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='comalu', verbose_name='Archivo')),
                ('turno', models.CharField(blank=True, choices=[('Ma', 'Matutino'), ('Ve', 'Vespertino'), ('Mi', 'Mixto')], max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Comunicados Alumnos Matutino',
                'verbose_name_plural': 'Comunicados Alumnos Matutino',
                'ordering': ['-created'],
            },
        ),
    ]
