# Generated by Django 2.1.3 on 2018-12-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0003_auto_20181129_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clavemate', models.CharField(blank=True, max_length=45, null=True)),
                ('materia', models.CharField(blank=True, max_length=45, null=True)),
                ('semestre', models.CharField(blank=True, max_length=45, null=True)),
                ('clavegrupo', models.CharField(blank=True, max_length=4, null=True)),
                ('parcial_1', models.CharField(blank=True, max_length=45, null=True)),
                ('parcial_2', models.CharField(blank=True, max_length=45, null=True)),
                ('parcial_3', models.CharField(blank=True, max_length=45, null=True)),
                ('calificaci', models.CharField(blank=True, max_length=45, null=True)),
                ('prompar', models.CharField(blank=True, max_length=45, null=True)),
                ('promsem', models.CharField(blank=True, max_length=45, null=True)),
                ('inasistenc', models.CharField(blank=True, max_length=45, null=True)),
                ('numclases', models.CharField(blank=True, max_length=45, null=True)),
                ('inasispar1', models.CharField(blank=True, max_length=45, null=True)),
                ('nclasespar', models.CharField(blank=True, max_length=45, null=True)),
                ('inasispar2', models.CharField(blank=True, max_length=45, null=True)),
                ('nclasespa2', models.CharField(blank=True, max_length=45, null=True)),
                ('inasispar3', models.CharField(blank=True, max_length=45, null=True)),
                ('nclasespa3', models.CharField(blank=True, max_length=45, null=True)),
                ('edoacredit', models.CharField(blank=True, max_length=45, null=True)),
                ('matricula', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='semestre',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
