# Generated by Django 2.1.3 on 2018-12-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0005_auto_20181207_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doch', models.CharField(max_length=30, verbose_name='Titulo')),
                ('gradogrupo', models.CharField(blank=True, max_length=10, verbose_name='Grado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comalu', verbose_name='Archivo')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='doch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gradogrupo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Grado'),
        ),
    ]
