# Generated by Django 2.1.3 on 2018-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0006_auto_20181207_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='gradogrupo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gradogrupo',
        ),
        migrations.AddField(
            model_name='horarios',
            name='grado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=2, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='user',
            name='grado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Grado'),
        ),
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], max_length=2, null=True, verbose_name='Grupo'),
        ),
    ]
