# Generated by Django 2.1.3 on 2018-12-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0007_auto_20181207_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='grado',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=2, null=True, verbose_name='Grado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grado',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=2, null=True, verbose_name='Grado'),
        ),
    ]
