# Generated by Django 2.1.3 on 2018-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0008_auto_20181207_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='doch',
            field=models.CharField(max_length=30, verbose_name='doch'),
        ),
    ]
