# Generated by Django 2.1.3 on 2018-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0009_auto_20181210_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='doch',
        ),
        migrations.RemoveField(
            model_name='horarios',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='doch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='semestre',
        ),
        migrations.AddField(
            model_name='horarios',
            name='asignatura',
            field=models.CharField(blank=True, max_length=20, verbose_name='asignatura'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='aula',
            field=models.CharField(blank=True, max_length=10, verbose_name='aulas'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='capacitacion',
            field=models.CharField(blank=True, max_length=20, verbose_name='capacitacion'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='docente',
            field=models.CharField(blank=True, max_length=40, verbose_name='docente'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='jueves',
            field=models.CharField(blank=True, max_length=10, verbose_name='jueves'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='lunes',
            field=models.CharField(blank=True, max_length=10, verbose_name='lunes'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='martes',
            field=models.CharField(blank=True, max_length=10, verbose_name='martes'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='miercoles',
            field=models.CharField(blank=True, max_length=10, verbose_name='miercoles'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='periodolec',
            field=models.CharField(blank=True, max_length=20, verbose_name='capacitacion'),
        ),
        migrations.AddField(
            model_name='horarios',
            name='turno',
            field=models.CharField(blank=True, choices=[('Ma', 'Matutino'), ('Ve', 'Vespertino')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='vierne',
            field=models.CharField(blank=True, max_length=10, verbose_name='viernes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
