# Generated by Django 2.1.4 on 2018-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0010_auto_20181211_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='periodolec',
            field=models.CharField(blank=True, max_length=20, verbose_name='capacitacion'),
        ),
    ]
