# Generated by Django 2.1.4 on 2019-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0013_auto_20190108_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='orden',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
