# Generated by Django 2.1.4 on 2019-01-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0014_calificacion_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='comunicadoescolar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='comalu', verbose_name='Imagen')),
                ('categoria', models.CharField(blank=True, choices=[('Di', 'Dibujo'), ('Ta', 'Taekwondo'), ('Ha', 'Hawaiano'), ('Da', 'Danza'), ('Ma', 'Marimba'), ('Vc', 'Vocalizacionycanto'), ('Bg', 'Bandadeguerra'), ('To', 'Tochito'), ('Es', 'Escolta'), ('Ba', 'Basquetbol'), ('Fu', 'Futbol'), ('Vo', 'Voleibol')], max_length=2, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'comunicado escolar',
                'verbose_name_plural': 'comunicados escolar',
                'ordering': ['-created'],
            },
        ),
    ]
