# Generated by Django 2.1.4 on 2019-01-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0018_auto_20190110_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadoescolar',
            name='image',
            field=models.FileField(upload_to='comalu', verbose_name='Imagen'),
        ),
    ]
