# Generated by Django 2.1.4 on 2019-01-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0020_auto_20190110_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadoescolar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comalu', verbose_name='Imagen'),
        ),
    ]
