# Generated by Django 2.1.4 on 2019-01-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0022_horarios_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fecha_nacimiento',
        ),
    ]
