# Generated by Django 2.1.4 on 2019-01-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0023_remove_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='grupo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
