# Generated by Django 2.1.4 on 2019-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0024_calificacion_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turno',
            field=models.CharField(blank=True, choices=[('Ma', 'Matutino'), ('Ve', 'Vespertino'), ('Mi', 'Mixto'), ('Di', 'Director'), ('Pa', 'Para-escolar')], max_length=2, null=True),
        ),
    ]
