# Generated by Django 2.1.4 on 2019-01-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0026_auto_20190114_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicadoescolar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paraescolar', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='comunicados_global',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='ComunicadosG', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Archivo'),
        ),
    ]
