# Generated by Django 2.1.4 on 2019-01-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0027_auto_20190114_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typeuser',
            field=models.CharField(blank=True, choices=[('Al', 'Alumno'), ('Do', 'Docente'), ('Di', 'Director'), ('Pa', 'Paraescolar')], max_length=2, null=True),
        ),
    ]
