# Generated by Django 2.1.4 on 2019-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0028_user_typeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='grado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2, null=True, verbose_name='Grado'),
        ),
    ]
