# Generated by Django 2.1.4 on 2019-01-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0030_auto_20190130_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='grado',
            field=models.CharField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=2, null=True, verbose_name='Grado'),
        ),
    ]
