# Generated by Django 2.1.4 on 2019-01-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0031_auto_20190130_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarios',
            name='archivo',
        ),
        migrations.AlterField(
            model_name='horarios',
            name='periodolec',
            field=models.CharField(blank=True, max_length=20, verbose_name='Perdiodo'),
        ),
    ]
