# Generated by Django 2.1.4 on 2019-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0037_auto_20190131_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='grado',
            field=models.FloatField(blank=True, choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto')], max_length=10, null=True, verbose_name='Grado'),
        ),
    ]
