# Generated by Django 2.1.4 on 2019-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0039_auto_20190131_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='grado',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Grado'),
        ),
    ]
