# Generated by Django 2.1.4 on 2019-02-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siscontrol', '0040_auto_20190131_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='rfc',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
